-- =============================================================================
-- Trailer model stage costs — drives the Production Report's WIP cost.
-- =============================================================================
-- Admin-set approximate dollar cost for each (trailer model, department) pair.
-- Mirrors point_values / dept_dollar_rates: effective-dated so editing a
-- value doesn't rewrite history.
--
-- Idempotent: table create + unique + index + FKs are all guarded.
-- Apply via prisma/apply-trailer-model-stage-costs.ts (db-seed workflow).
-- =============================================================================

CREATE TABLE IF NOT EXISTS trailer_model_stage_costs (
  id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trailer_model_id  INT            NOT NULL,
  department_id     INT            NOT NULL,
  cost_dollars      DECIMAL(10, 2) NOT NULL,
  effective_from    DATE           NOT NULL,
  effective_to      DATE           NULL,
  UNIQUE (trailer_model_id, department_id, effective_from)
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'trailer_model_stage_costs_trailer_model_id_fkey'
      AND table_name = 'trailer_model_stage_costs'
  ) THEN
    ALTER TABLE trailer_model_stage_costs
      ADD CONSTRAINT trailer_model_stage_costs_trailer_model_id_fkey
      FOREIGN KEY (trailer_model_id) REFERENCES trailer_models(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE constraint_name = 'trailer_model_stage_costs_department_id_fkey'
      AND table_name = 'trailer_model_stage_costs'
  ) THEN
    ALTER TABLE trailer_model_stage_costs
      ADD CONSTRAINT trailer_model_stage_costs_department_id_fkey
      FOREIGN KEY (department_id) REFERENCES departments(id);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_stage_costs_model_dept
  ON trailer_model_stage_costs (trailer_model_id, department_id);
