// =============================================================================
// BIGFOOT TRAILERS — One-shot: create trailer_model_stage_costs table
//
// Mirrors prisma/sql-patches/2026-06-19_add_trailer_model_stage_costs.sql.
// Runs through Prisma's $executeRawUnsafe so the db-seed GitHub Actions
// workflow can apply it without psql.
//
// Drives the WIP cost summary on the new Production Report screen — admin
// sets approx dollar cost per (trailer model, department), and the report
// sums the matrix across each in-flight trailer's completed steps to
// estimate invested cost.
//
// Idempotent: table / unique / FK / index are all guarded.
// =============================================================================

import 'dotenv/config';
import { createPrismaClient } from './db-client';

const prisma = createPrismaClient();

async function main(): Promise<void> {
  console.log('💰 Creating trailer_model_stage_costs table (idempotent)...\n');

  await prisma.$executeRawUnsafe(`
    CREATE TABLE IF NOT EXISTS trailer_model_stage_costs (
      id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      trailer_model_id  INT            NOT NULL,
      department_id     INT            NOT NULL,
      cost_dollars      DECIMAL(10, 2) NOT NULL,
      effective_from    DATE           NOT NULL,
      effective_to      DATE           NULL,
      UNIQUE (trailer_model_id, department_id, effective_from)
    );
  `);
  console.log('  ✅ table present');

  await prisma.$executeRawUnsafe(`
    DO $$
    BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'trailer_model_stage_costs_trailer_model_id_fkey'
          AND table_name = 'trailer_model_stage_costs'
      ) THEN
        ALTER TABLE trailer_model_stage_costs
          ADD CONSTRAINT trailer_model_stage_costs_trailer_model_id_fkey
          FOREIGN KEY (trailer_model_id) REFERENCES trailer_models(id);
      END IF;

      IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'trailer_model_stage_costs_department_id_fkey'
          AND table_name = 'trailer_model_stage_costs'
      ) THEN
        ALTER TABLE trailer_model_stage_costs
          ADD CONSTRAINT trailer_model_stage_costs_department_id_fkey
          FOREIGN KEY (department_id) REFERENCES departments(id);
      END IF;
    END $$;
  `);
  console.log('  ✅ FKs present');

  await prisma.$executeRawUnsafe(
    `CREATE INDEX IF NOT EXISTS idx_stage_costs_model_dept
       ON trailer_model_stage_costs (trailer_model_id, department_id);`,
  );
  console.log('  ✅ idx_stage_costs_model_dept present');

  console.log('\n🎉 Done. Admin can now populate the production cost matrix.');
}

main()
  .catch((e) => {
    console.error('❌ Migration failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
